# Generated by Django 3.2 on 2021-10-09 14:42

import utils.validators.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='gas_capacity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='gas_count',
            field=models.PositiveIntegerField(default=0, validators=[utils.validators.validators.PorcentagemValidator]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
