# Generated by Django 3.2 on 2021-10-11 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_auto_20211009_1206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tyremodel',
            old_name='is_active',
            new_name='in_use',
        ),
        migrations.AlterField(
            model_name='tyremodel',
            name='degradation',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
