# Generated by Django 3.2 on 2021-10-11 03:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20211011_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='gas_capacity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='tyremodel',
            name='degradation',
            field=models.FloatField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
