# Generated by Django 3.2 on 2021-10-11 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0005_auto_20211011_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='gas_count',
            field=models.PositiveIntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
