# Generated by Django 3.2 on 2021-10-11 05:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_carmodel_gas_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='gas_count',
            field=models.FloatField(default=100, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
